### ISSUE TITLE
Partial updates / add missing versions

### ISSUE THREAD

**Issue by estahn** [github-changelog-generator/github-changelog-generator#209]
It would be great if the generator doesn't replace the entire file but just adds missing versions and ignores existing ones. We have some manual added information which we don't want to lose when generating the changelog.

**Features:**
- Ability to keep manual added information for older version tags
- Reduced GitHub API calls due to reduce amount of data necessary to retrieve
- Stop/continue a changelog generation process due to partial updates  

**Implementation:**
The CHANGELOG.md needs to be parsed and divided into sections which represent the versions, e.g.

``` ruby
[{ :version => 'v0.0.1', :content => '...' }, { :version => 'v1.0.0', :content => '...' }, ...]
```

Missing versions can be fetched from the GitHub API and appended.

This might be related to #172.

**Comment by skywinder** [comment]
@estahn thanks for feature request! It would be a great addition :boom:  , but it has a lot of work to implement this.
It can be slitted for a several little sub-tasks:

- So, first part: #172 is already implemented. I will release it soon.
- The similar feature, that I want to implement to help with custom parsing is: Generate change log since/due specific date #210
- The next step will be implement partial update of the `CHANGELOG.md`. i.e. fetch only specific issues (between specific tags, or between time) and not modify others. i.e. some thing like `--amend` command. #211
- Another thing is a parsing of existing Change log file.#212
- And finally: Ability to keep manual added information for older version tags #213

**Comment by skywinder** [comment]
@estahn  I created special repo for test, how generator works. 
https://github.com/skywinder/changelog_test
Feel free to modify it to test new features.

**Comment by skywinder** [comment]
This issue has been closed as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. 
Feel free to leave a comment below, if it's still actual.
