### ISSUE TITLE
Any suggestion about _when_ running this scrip?

### ISSUE THREAD

**Issue by ignazioc** [github-changelog-generator/github-changelog-generator#672]
I love this tool, it's saving me so much time but I didn't figured out yet when it's the best moment to run ti.
I'm using gitflow and I run this script when I create a release candidate branch.
The result is that all the new PR/Issues are marked as `Unreleased`

I also tried to run it directly on `master` after that `develop` is merged. This is not always possible for policy reasons and may require an additional pull request.

how you configured this repository?

**Comment by skywinder** [comment]
I have a script that bumps versions and updates changelog according to git-flow scheme.
You can check, how it's implemented here: https://github.com/skywinder/bumper_pusher

It looks pretty ugly (since it was my second project on ruby, but the main idea is straightforward)
https://github.com/skywinder/bumper_pusher/blob/8b6a2f8fb25237da3757b88dcad35cc7cb1f6b24/lib/bumper_pusher/bumper.rb#L346

**Comment by skywinder** [comment]
@olleolleolle I remember you do a bunch of things with `rake`.
Is this tool can help with in this situation?

**Comment by mob-sakai** [comment]
> The result is that all the new PR/Issues are marked as `Unreleased`

Use `--future-release  [RELEASE-VERSION]` option.
It will replace unreleased section with release version, without tagging.

```
future-release [RELEASE-VERSION]

Put the unreleased changes in the specified release number.

This will replace Unreleased section with the specified tag. Handy for generating change logs before tagging.
```

**Comment by ignazioc** [comment]
Nice thanks !

**Comment by skywinder** [comment]
Closing in favor of improvement #683
@ignazioc Feel free to reopen the issue if you still need help. 👍
