### ISSUE TITLE
generate changelog from two repos

### ISSUE THREAD

**Issue by josesimoes** [github-changelog-generator/github-changelog-generator#673]
Hi,

At nanoFramework we are running a project that has several repos. Because the issues usually touch more than one project, we have them centralised at the Home repo. The usual development workflow occurs in the individual repos (PRs, merges, etc)
When generating the change log for one of the repos we would like to use the PRs and tags from the "self" repo _and_ link to the issues that are on the "home" repo.
Is this something that can be accomplished with the current version?

**Comment by olleolleolle** [comment]
Short answer: No.

**Comment by skywinder** [comment]
hi, @josesimoes there was similar issues about this case. 
Here is 
1) a several difficulties with automatic parsing and merges issues from forked repos 
2) logically the correct case to generate history since the fork.

But it could be possible to put previous history changelog part as prefix. here is very old and wanted feature.  #213 I believe that what you need and will help you. feel free to +1 it 👍

**Comment by skywinder** [comment]
related with #472

**Comment by skywinder** [comment]
and dup of #252

**Comment by josesimoes** [comment]
Hi @skywinder ! Thanks for looking into this. I believe it's more with #252 than with forked repos.
I've added my comment there as upvote. 

BTW, great work you guys have done here! 👏
