### ISSUE TITLE
Add PR that are not linked to an issue

### ISSUE THREAD

**Issue by renehernandez** [github-changelog-generator/github-changelog-generator#890]
Is a there way to limit the PRs in the changelog to those that are not linked to any issue?  

I have researched the documentation, but I couldn't find anything related to it so far.

**Comment by renehernandez** [comment]
@dlanileonardo any ideas? Is that something that it would need to be implemented?

**Comment by dlanileonardo** [comment]
Hi @renehernandez 

I think this is difficult for this moment, because the Github Api doesn't have linked issues feature in pull request field or endpoint. Just have this feature in [GraphQL API](https://developer.github.com/v4/).

I suggest you can use ```filter-by-milestone``` to control or ```exclude-labels```. I have been used this second, I created **no-changelog** label and i assigned in my issues and pull-requests to ignore-it.
